### ISSUE TITLE
CUDA out of mem error on large temporal sets

### ISSUE THREAD

**Issue by heisenbugfix** [yule-BUAA/DNNTSP#1]
I tried running the code with batch size 1 on a dataset where number of items are in order of 100-1000 across all sets in a datapoint. It fails with CUDA out of mem error. Specifically the code fails at:
https://github.com/yule-BUAA/DNNTSP/blob/master/model/weighted_graph_conv.py#L35

Is there any way to optimize the size of the edge_weights considering the fact that if we have say 600 nodes then size of edge weight comes around `30x360000` where `30` is the number of sets in a single datapoint.

Do you suggest optimization at a different step?

**Comment by yule-BUAA** [comment]
Thanks for your interest in our work.

The revised version by [Zihao Ye](https://github.com/yzh119) has been merged into the master branch, which eliminates the User Defined Function (UDF) and uses `dgl.function` to reduce the requirement of GPU memory and accelerate the training speed. 

Please note that the version of dgl was updated to 0.5 as well.

If you still have any questions, welcome to contact us.

Best wishes,
Le Yu

**Comment by heisenbugfix** [comment]
Thanks. The code runs with batch size 2. With batch size > 2, it still gives cuda mem error in back pass. Maybe creating graphs separately for each temporal set in a datapoint might help. That way number of edges `edge_weights` data can be significantly reduced. Closing this issue for now.
